package core

import (
	"fmt"
	"strings"
)

// Compose generation. Two shapes umbra writes itself (never a YAML parser — it
// only ever emits YAML it fully controls):
//
//  1. A minimal service from a bare image (deploy --image).
//  2. A network override that joins a chosen service to the shared `umbra`
//     bridge with a stable alias, so Caddy can reach it by app name across
//     compose-project boundaries.

// synthesizeImageCompose synthesizes a one-service compose for a bare image.
// The service is named after the app so its default alias on the umbra network
// is the app name, which is exactly what the proxy route targets.
func synthesizeImageCompose(app, image string, port int) string {
	var b strings.Builder
	fmt.Fprintf(&b, "# Generated by umbra for app %q. Edit at your own risk — umbra may rewrite it.\n", app)
	b.WriteString("services:\n")
	fmt.Fprintf(&b, "  %s:\n", app)
	fmt.Fprintf(&b, "    image: %s\n", image)
	b.WriteString("    restart: unless-stopped\n")
	if port != 0 {
		// `expose` documents the container port for humans; routing is over the
		// shared network, so we intentionally do NOT publish a host port here.
		b.WriteString("    expose:\n")
		fmt.Fprintf(&b, "      - \"%d\"\n", port)
	}
	return b.String()
}

// networkOverride is the override that attaches `service` to the external umbra
// network with the app name as its alias. Applied with a second `-f` so it
// merges onto whatever compose the app already has, whether umbra synthesized
// it or the user wrote it.
func networkOverride(app, service string) string {
	return strings.Join([]string{
		fmt.Sprintf("# Generated by umbra — joins %q to the shared umbra proxy network.", service),
		"networks:",
		"  " + UmbraNetwork + ":",
		"    external: true",
		"services:",
		"  " + service + ":",
		"    networks:",
		"      " + UmbraNetwork + ":",
		"        aliases:",
		"          - " + app,
		"",
	}, "\n")
}
