/**
 * Compose generation. Two shapes umbra writes itself (never a YAML parser —
 * it only ever emits YAML it fully controls):
 *
 *  1. A minimal service from a bare image (`deploy --image`).
 *  2. A network override that joins a chosen service to the shared `umbra`
 *     bridge with a stable alias, so Caddy can reach it by app name across
 *     compose-project boundaries.
 */
import { UMBRA_NETWORK } from "./paths.js";

/**
 * Synthesize a one-service compose for a bare image. The service is named
 * after the app so its default alias on the umbra network is the app name,
 * which is exactly what the proxy route targets.
 */
export function synthesizeImageCompose(app: string, image: string, port?: number): string {
  const lines: string[] = [];
  lines.push(`# Generated by umbra for app "${app}". Edit at your own risk — umbra may rewrite it.`);
  lines.push(`services:`);
  lines.push(`  ${app}:`);
  lines.push(`    image: ${image}`);
  lines.push(`    restart: unless-stopped`);
  if (port) {
    // `expose` documents the container port for humans; routing is over the
    // shared network, so we intentionally do NOT publish a host port here.
    lines.push(`    expose:`);
    lines.push(`      - "${port}"`);
  }
  return lines.join("\n") + "\n";
}

/**
 * The override that attaches `service` to the external umbra network with the
 * app name as its alias. Applied with a second `-f` so it merges onto whatever
 * compose the app already has, whether umbra synthesized it or the user wrote it.
 */
export function networkOverride(app: string, service: string): string {
  return [
    `# Generated by umbra — joins "${service}" to the shared umbra proxy network.`,
    `networks:`,
    `  ${UMBRA_NETWORK}:`,
    `    external: true`,
    `services:`,
    `  ${service}:`,
    `    networks:`,
    `      ${UMBRA_NETWORK}:`,
    `        aliases:`,
    `          - ${app}`,
    ``,
  ].join("\n");
}
